# Generated by Django 4.2.2 on 2023-06-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('invcode', models.CharField(max_length=100)),
                ('index', models.IntegerField(choices=[(0, '管理员'), (1, '经理'), (2, '客户')], default=2)),
            ],
        ),
    ]
