# Generated by Django 4.2.2 on 2023-06-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='index',
            field=models.IntegerField(choices=[(0, '管理员'), (1, '经理'), (2, '客户')], default=2),
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='invcode',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
