# Generated by Django 4.2.2 on 2023-06-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_accountinfo_invcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
