# Generated by Django 4.2.2 on 2023-06-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accountinfo_index_accountinfo_invcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountinfo',
            old_name='index',
            new_name='accountindex',
        ),
    ]
