# Generated by Django 4.2.2 on 2023-06-23 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_cookie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookie',
            old_name='code',
            new_name='cookie',
        ),
        migrations.RemoveField(
            model_name='cookie',
            name='init_time',
        ),
        migrations.RemoveField(
            model_name='cookie',
            name='period',
        ),
        migrations.AddField(
            model_name='cookie',
            name='expiration',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
