# Generated by Django 4.2.2 on 2023-06-24 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_rename_code_cookie_cookie_remove_cookie_init_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial_type',
            fields=[
                ('financial_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='理财项目编号')),
                ('financial_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance_type',
            fields=[
                ('insurance_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='保险编号')),
                ('insurance_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='financial_project',
            name='financial_project_name',
        ),
        migrations.RemoveField(
            model_name='insurance_project',
            name='insurance_project_name',
        ),
        migrations.AddField(
            model_name='financial_project',
            name='financial_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bank.financial_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurance_project',
            name='insurance_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bank.insurance_type'),
            preserve_default=False,
        ),
    ]
