# Generated by Django 4.2.2 on 2023-06-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_rename_manager_with_currency_project_manager_with_fund_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='financial',
            field=models.ManyToManyField(through='bank.manager_with_financial', to='bank.financial_type'),
        ),
        migrations.AddField(
            model_name='manager',
            name='fund',
            field=models.ManyToManyField(through='bank.manager_with_fund', to='bank.fund_type'),
        ),
        migrations.AddField(
            model_name='manager',
            name='insurance',
            field=models.ManyToManyField(through='bank.manager_with_insurance', to='bank.insurance_type'),
        ),
    ]
